#include "SteppingAction.hh"
#include "G4Step.hh"
#include "G4Track.hh"
#include "G4SystemOfUnits.hh"
#include "G4Threading.hh"
#include "G4UnitsTable.hh"

SteppingAction::SteppingAction()
    : G4UserSteppingAction(), fInitialEnergy(0.0), fGeneratedParticles(0)
{
}

SteppingAction::~SteppingAction()
{
  if (G4Threading::IsMasterThread())
  {
    G4cout
        << "\n Total Particles Generated by GPS: " << fGeneratedParticles
        << "\n Total Initial Energy Generated:   " << G4BestUnit(fInitialEnergy, "Energy")
        << G4endl;
  }
}

void SteppingAction::UserSteppingAction(const G4Step *step)
{

  if (step->GetTrack()->GetCurrentStepNumber() != 1)
  {
    return;
  }

  if (step->GetTrack()->GetParticleDefinition()->GetParticleName() == "e-")
  {

    G4double initialEnergy = step->GetTrack()->GetVertexKineticEnergy();

    std::lock_guard<std::mutex> lock(fMutex);
    fInitialEnergy += initialEnergy;
    fGeneratedParticles++;
  }
}